Update 11111

diff --git a/11111 b/11111
--- a/11111
+++ b/11111
@@ -1,12 +1,183 @@
+
+#!/usr/bin/env bash
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
+usage() {
+cat<<EOF
+Скрипт предназначен для создания юнита 
+Команды для работы:
+-h, —help
+-d -- name code, создает юнит без автозапуска
+-e -- name code, создает юнит с автозапуска
+EOF
+
+exit
+
+}
+
+cleanup() {
+trap - SIGINT SIGTERM ERR EXIT
+# script cleanup here
+}
+
+setup_colors() {
+if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m'
+BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+else
+NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+fi
+
+}
+msg() {
+echo >&2 -e "${1-}"
+
+}
+
+die() {
+local msg=$1
+local code=${2-1} # default exit status 1
+msg "$msg"
+exit "$code"
+}
+
+
+ecreate(){
+
+count=1
+name=""
+code=""
+
 while [ -n "$1" ]
 do
 case "$1" in
--a) echo "Found the -a option" ;;
--b) echo "Found the -b option";;
--c) echo "Found the -c option" ;;
 --) shift
 break ;;
-*) echo "$1 is not an option";;
+*) echo "";;
 esac
 shift
 done
+
+for param in $@
+do
+
+if(($count != 1))
+then
+   code+="$param "
+fi
+
+if(($count == 1))
+then
+   name+=$param
+   count=$(( $count + 1))
+fi
+
+done
+
+sudo touch "/etc/systemd/system/$name.service"
+sudo chmod a+w "/etc/systemd/system/$name.service"
+sudo cat << EOF > "/etc/systemd/system/$name.service"
+[Unit]
+Description=My Shell Script
+
+[Service]
+ExecStart=$code
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+sudo systemctl daemon-reload
+sudo systemctl enable "$name.service"
+sudo systemctl status "$name.service"
+
+exit "1"
+}
+
+
+
+dcreate(){
+
+count=1
+name=""
+code=""
+
+while [ -n "$1" ]
+do
+case "$1" in
+--) shift
+break ;;
+*) echo "";;
+esac
+shift
+done
+
+for param in $@
+do
+
+if(($count != 1))
+then
+   code+="$param "
+fi
+
+if(($count == 1))
+then
+   name+=$param
+   count=$(( $count + 1))
+fi
+
+done
+
+sudo touch "/etc/systemd/system/$name.service"
+sudo chmod a+w "/etc/systemd/system/$name.service"
+sudo cat << EOF > "/etc/systemd/system/$name.service"
+[Unit]
+Description=My Shell Script
+
+[Service]
+ExecStart=$code
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+sudo systemctl daemon-reload
+sudo systemctl disable "$name.service"
+sudo systemctl status "$name.service"
+
+exit "1"
+}
+
+
+parse_params() {
+# default values of variables set from params
+flag=0
+param="${@}"
+
+
+while :; do
+case "$1" in
+-h | --help) usage ;;
+-e | --ecreate) ecreate $param;;
+-d | --dcreate) dcreate $param
+param="${2-}"
+shift
+;;
+-?*) die "Unknown option: $1" ;;
+*) break ;;
+esac
+shift
+done
+args=("$@")
+
+msg "${@}"
+
+# check required params and arguments
+[[ -z "${param-}" ]] && die "Missing required parameter: param"
+[[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+return 0
+}
+setup_colors
+parse_params "$@"
+#setup_colors
